[package]
name = "wslcmd"
version = "0.9.2"
edition = "2018"

[dependencies]
derive-getters = "0.2.0"
regex = "1.5.4"
termcolor = "1.1.2"
lnk = "0.3.0"
winreg = "0.10"
winapi = {version = "0.3", features = ["winnt"]}
