[package]
name = "wsllink"
version = "0.1.0"
edition = "2018"

[dependencies]
derive-getters = "0.2.0"
regex = "1.5.4"
termcolor = "1.1.2"
itertools = "0.10.1"
#winapi = {version = "0.3", features = ["wincon", "winuser"]}
#windows = "0.19.0"

[build-dependencies]
#windows = "0.19.0"
