[alias]

build-gnu = ["build", "--target", "x86_64-pc-windows-gnu"]
check-gnu = ["check", "--target", "x86_64-pc-windows-gnu"]
test-gnu = ["test", "--target", "x86_64-pc-windows-gnu", "--", "--test-threads=1"]
run-gnu = ["run", "--target", "x86_64-pc-windows-gnu"]
doc-gnu = ["doc", "--target", "x86_64-pc-windows-gnu"]

bg = ["build", "--target", "x86_64-pc-windows-gnu"]
cg = ["check", "--target", "x86_64-pc-windows-gnu"]
tg = ["test", "--target", "x86_64-pc-windows-gnu", "--", "--test-threads=1"]
rg = ["run", "--target", "x86_64-pc-windows-gnu"]
dg = ["doc", "--target", "x86_64-pc-windows-gnu"]

build-msvc = ["build", "--target", "x86_64-pc-windows-msvc"]
check-msvc = ["check", "--target", "x86_64-pc-windows-msvc"]
test-msvc = ["test", "--target", "x86_64-pc-windows-msvc", "--", "--test-threads=1"]
run-msvc = ["run", "--target", "x86_64-pc-windows-msvc"]
doc-msvc = ["doc", "--target", "x86_64-pc-windows-msvc"]

bm = ["build", "--target", "x86_64-pc-windows-msvc"]
cm = ["check", "--target", "x86_64-pc-windows-msvc"]
tm = ["test", "--target", "x86_64-pc-windows-msvc", "--", "--test-threads=1"]
rm = ["run", "--target", "x86_64-pc-windows-msvc"]
dm = ["doc", "--target", "x86_64-pc-windows-msvc"]
