[alias]

build-gnu = ["build", "--target", "x86_64-pc-windows-gnu"]
check-gnu = ["check", "--target", "x86_64-pc-windows-gnu"]
test-gnu = ["test", "--target", "x86_64-pc-windows-gnu"]
run-gnu = ["run", "--target", "x86_64-pc-windows-gnu"]

bg = ["build", "--target", "x86_64-pc-windows-gnu"]
cg = ["check", "--target", "x86_64-pc-windows-gnu"]
tg = ["test", "--target", "x86_64-pc-windows-gnu"]
rg = ["run", "--target", "x86_64-pc-windows-gnu"]

build-msvc = ["build", "--target", "x86_64-pc-windows-msvc"]
check-msvc = ["check", "--target", "x86_64-pc-windows-msvc"]
test-msvc = ["test", "--target", "x86_64-pc-windows-msvc"]
run-msvc = ["run", "--target", "x86_64-pc-windows-msvc"]

bm = ["build", "--target", "x86_64-pc-windows-msvc"]
cm = ["check", "--target", "x86_64-pc-windows-msvc"]
tm = ["test", "--target", "x86_64-pc-windows-msvc"]
rm = ["run", "--target", "x86_64-pc-windows-msvc"]